_target_: detector.models.regressor.Regressor
backbone:
  _target_: detector.models.models.DenseNet
  pretrained: True
head:
  _target_: detector.models.head.Regressor
  in_features: 26624
  out_features: 1942