_target_: detector.models.regressor.Regressor
backbone:
  _target_: detector.models.models.ResNet18
  pretrained: False
head:
  _target_: detector.models.head.Regressor
  in_features: 1000
  out_features: 971