# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - data: data.yaml
  - model: densenet169.yaml
  - loss: l1l2.yaml
  - optimizer: adam.yaml
#  - callbacks: default.yaml
  - logger: null # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
#  - trainer: default.yaml
#  - log_dir: default.yaml

  # experiment configs allow for version control of specific configurations
  # e.g. best hyperparameters for each combination of model and datamodule
#  - experiment: resnet18

# path to original working directory
# hydra hijacks working directory by changing it to the new log directory
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
original_work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${original_work_dir}/data/

# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: True

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

checkpoint_file: null

# seed for random number generators in pytorch, numpy and python.random
seed: 3407

num_gpus: null

# number of facial points
num_pts: 971

num_workers: 0
batch_size: 16
batch_size_inference: 8
epochs: 5
# default name for the experiment, determines logging folder path
# (you can overwrite this name in experiment configs)
name: "resnet18"
logger: ${original_work_dir}/configs/logger.yaml